services:
#    daemon_filestorage.example:
#        class: Daemon\FilestorageBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    daemon_filestorage:
        class: Daemon\FilestorageBundle\Component\FileStorage
        arguments: 
            - @kernel
            - @doctrine.orm.entity_manager

    daemon_filestorage.twig.extension.image_by_hash:
        class: Daemon\FilestorageBundle\Twig\ImageExtension
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }
